---
- hosts: raspberries
  become: true

  tasks:
    - name: Load Configuration Variables
      include_vars: ../config.yml

    - name: Copy docker files
      copy: 
        src: ../docker
        dest: /home/pi
        owner: pi
        group: pi

    - name: Copy influxdb initial script variables
      template: 
        src: ../templates/create-db.iql.j2
        dest: /home/pi/docker/influxdb/init/create-db.iql
        owner: pi
        group: pi    

    - name: Copy docker compose environmental variables
      template: 
        src: ../templates/docker.env.j2
        dest: /home/pi/docker/.env
        owner: pi
        group: pi

    - name: Start containers
      command: docker-compose up -d
      become_user: pi
      args:
        chdir: /home/pi/docker
      

        